### ISSUE TITLE
Every type name registered with a wasm Module by djinni must be unique

### ISSUE THREAD

**Issue by finalpatch** [Snapchat/djinni#52]
Currently our wasm codegen does not support having 2 top level types with the same name even when they are from different djinni idl files.  This is because top level names are exported to the wasm Module object by just their names, without the namespaces.

We can potentially include namespaces in the export names, but we need support on Emscripten side to allow nested names. This limitation of Emscripten is reported here  https://github.com/emscripten-core/emscripten/issues/15474

A workaround is to include namespaces with underscores, eg. `namespace1_InterfaceName`.  But this is much less nice than having true namespaces.

**Comment by bkotsopoulossc** [comment]
Some other options we have discussed, beyond the underscores and emscripten fix mentioned above:
- Reimplement all or parts of embind
- Generate names with underscores and then post-process to alias them

**Comment by bkotsopoulossc** [comment]
Okay so with https://github.com/Snapchat/djinni/pull/53 closed, we no longer have consts or enums conflicting on the Module object. Djinni records aren't registered with the module, so only djinni interfaces can now conflict. So any djinni interfaces built into a single module need to have unique names.

We should take advantage of an observation. When djinni interfaces are registered with a module through embind::class, the instance functions (and destructor) are never accessed from Module, because they are accessed on the individual objects. The constructor *could* be accessed from the Module directly, but that goes against how djinni works. Djinni does not expose constructors for types - instead it forces you into a factory pattern, where the only way to create an instance of a djinni interface across a language boundary is to call a static function that returns the interface. So TLDR, we don't care about the constructors from Module because we don't use them.

The only part of a djinni interface registered to a Module that we care about is the class functions. This doesn't solve our problem, it just scopes it. 

So let's say we had these interfaces:
```
// foo.djinni
interface Dog = {
  static create(): Dog;
  doSomething();
}

// bar.djinni
interface Dog = {
  static create(): Dog;
  doSomethingElse();
}
```

So if we did the underscores solution, the only time we'd be using the verbose syntax would be when we call the statics, like:
```
Module.bar_Dog.create()
Module.foo_Dog.create()
```

That alone isn't too bad.

**Comment by bkotsopoulossc** [comment]
I think our ideal state would be the following.

Static functions are accessed through the object hierarchy:
```
Module.bar.Dog.create()
Module.foo.Dog.create()
```

But the individual classes can be registered to the module with underscores because we never use them otherwise:
```
Module.this_can_be_verbose_bar_Dog
Module.this_can_be_verbose_foo_Dog
```

**Comment by bkotsopoulossc** [comment]
One observation is, with our usage of classes, there is no benefit to registering a class function. So what we do:
```
    emscripten::class_<Dog>("Dog")
        .smart_ptr<std::shared_ptr<Dog>>("Dog")
        .class_function("create", Dog::create)
        ....
        ;
```

Can also be achieved (with a different naming on the Module object) as:
```
    emscripten::function("Dog_create", &Dog::create);
    emscripten::class_<Dog>("Dog")
        .smart_ptr<std::shared_ptr<Dog>>("Dog")
        ....
        ;
```

This decouples the naming (and uniqueness constraints) for the object vs the statics

**Comment by bkotsopoulossc** [comment]
I explored this a bit and I think the simplest option is to take these lines https://github.com/Snapchat/djinni/blob/fa64e7566803cdd3fb4488b59ed35c25b64b7916/src/source/WasmGenerator.scala#L386-L387, and prefix them with something like this https://github.com/Snapchat/djinni/blob/fa64e7566803cdd3fb4488b59ed35c25b64b7916/src/source/WasmGenerator.scala#L163.

And then update the names for interfaces in typescript to match https://github.com/Snapchat/djinni/blob/fa64e7566803cdd3fb4488b59ed35c25b64b7916/src/source/TsGenerator.scala#L190.
