### ISSUE TITLE
Java: `CppProxy.destroyed` is never set to `true`

### ISSUE THREAD

**Issue by derolf** [Snapchat/djinni#82]
Each `CppProxy` declares a field:

```

private final AtomicBoolean destroyed = new AtomicBoolean(false);
```

That field is used to verify that objects haven't been destroyed when using, like this:

```
assert !this.destroyed.get() : "trying to use a destroyed object";
```

However, I am missing the code, where `destroyed` is actually set to `true`.

**Comment by LiFengSC** [comment]
Hi derolf, 

I think the `destroyed` field is a historic relic that existed before I rewrote the lifetime management mechanism with phantom references.  As far as I can see there really isn't a way to call a proxy method after the `nativeDestroy` method is called, because in order for that method to be called, the JVM has already dropped all references to the proxy object.

This field, as well as the assertion on it,  should just be removed.

**Comment by derolf** [comment]
In theory, a dead proxy could be called if someone does “finalizer resurrection”.

**Comment by LiFengSC** [comment]
The cpp proxy objects do not have finalises and there is no way to add one as these classes are final.

**Comment by derolf** [comment]
Thanks for clarifying!
